### ISSUE TITLE
setup.sh does not handle region gke cluster

### ISSUE THREAD

**Issue by wilddog64** [GoogleCloudPlatform/spinnaker-for-gcp#141]
If the GKE is configured as a regional cluster, the setup script does not handle it. This is because  gcloud container clusters get-credentials *$GKE_CLUSTER --zone $ZONE --project $PROJECT_ID* is use --zone instead of --region. This also happen at one of the functions in cluster_utils. Also the push_config.sh only check ZONE but ignore REGION. Ideally these scripts should handle both region and zone to cover all cases.

**Comment by demobox** [comment]
Thanks for reporting this, @wilddog64! I'll let the team comment on potential motivations here, but agree that this should at very least be documented.

/cc @dorbin on that

**Comment by wilddog64** [comment]
I am sure like to do that. I also think it is better to have gcloud to
support --location, which can dramatically solve the problem.

**Comment by demobox** [comment]
> I also think it is better to have gcloud to support --location, which can dramatically solve the problem.

Agreed!

**Comment by duftler** [comment]
This PR adds logic to verify location of pre-existing cluster and aborts the installation if it is regional: #146.

**Comment by demobox** [comment]
Hopefully, with #146 we will at least fail in a less confusing way. This issue is still accurate in that regional GKE clusters are still not supported, but I'd suggest closing it out for now as we are not planning to address this in the short term.

If there is any interest in contributing this functionality via a pull request, we'd definitely be keen to discuss that!
