### ISSUE TITLE
Documentation on audit log cloud function

### ISSUE THREAD

**Issue by stevenaldinger** [GoogleCloudPlatform/spinnaker-for-gcp#93]
The `spinnakerAuditLog` cloud function looks great but I can't figure out how to view the logs. I ended up adding a `console.log` right above the `log.write(entry);` line which works fine, but feels like it defeats the purpose of using the `@google-cloud/logging` module.

Some documentation around how to view the logs would be great!

Thanks!

**Comment by duftler** [comment]
Shouldn't need to make any changes to the function to see the log entries.

The Audit Log cloud function writes log entries to Stackdriver. The Stackdriver entries can be found via links in the management console: 
![image](https://user-images.githubusercontent.com/8437718/62623340-99964480-b8ee-11e9-90aa-6dc013fd1b79.png)

Or from the GKE Applications details view: 
![image](https://user-images.githubusercontent.com/8437718/62623359-a2871600-b8ee-11e9-9899-1e19986b719b.png)

The Stackdriver log entries should look like so: 
![image](https://user-images.githubusercontent.com/8437718/62623392-b6327c80-b8ee-11e9-92fb-705250975d98.png)

**Comment by stevenaldinger** [comment]
Thanks for the quick response! We're using a preexisting Spinnaker cluster so can't take advantage of the management console, the stackdriver log entry screenshot was really helpful. I feel like there may be missing permissions or something, when I go to stackdriver I only see the "function execution" messages. Does that sound like a possibility to you or would it error out instead of status code: 200?
![Screen Shot 2019-08-07 at 10 31 43 AM](https://user-images.githubusercontent.com/11810790/62631375-a15de500-b8fe-11e9-8abb-7fde15ea23d0.png)

**Comment by duftler** [comment]
I think that logs ui is sometimes not so intuitive. Several things have helped me when I go looking for log entries from cloud functions:

1) The cloud function's name doesn't show up as a choice anywhere until after log entries have been recorded (so you must have done some work with Spinnaker since configuring the audit log, and given the events a little time to propagate all the way to the logging service)
2) In that left-most pulldown, where you select a resource, just select "Cloud Function", not the more-specific "Cloud Function->spinnaker1AuditLog"
3) Once you've chosen to view the logs of all cloud functions, the pulldown just to the right should list all log names to choose from; choose "spinnaker1AuditLog": 
![image](https://user-images.githubusercontent.com/8437718/62636069-e2f28e00-b906-11e9-9cd9-39d2de5b7785.png)

**Comment by stevenaldinger** [comment]
That worked! Thank you so much for the help and for open sourcing the auditing tool to begin with!

**Comment by duftler** [comment]
Sweet.
